## Problem 1: NumPy Array – Sum of Diagonal Elements
### Objective

- Create a square matrix using user input and calculate the sum of its diagonal elements using a loop.

In [1]:
import numpy as np

In [4]:
# User input for matrix order
n = int(input("Enter the order of the matrix (e.g., 2 for 2x2): "))

print("Enter the elements row-wise:")

# Creating matrix using user input
matrix = np.zeros((n, n), dtype=int)

for i in range(n):
    for j in range(n):
        matrix[i][j] = int(input(f"Element [{i}][{j}]: "))

# Display matrix
print("\nMatrix:")
print(matrix)


Enter the elements row-wise:

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Calculate sum of diagonal elements
diagonal_sum = 0
for i in range(n):
    diagonal_sum += matrix[i][i]

# Output
print("\nSum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 15
